name: CI Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t sys-info-app .

      - name: Test Docker Container
        run: |
          docker run --rm sys-info-app -d

      - name: Test Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps

      - name: Run ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          shellcheck sys_info.sh
